Map<String, String> ar= {
 'appName':'         دراسة الجدوى',
 'language':'اللغة',
 'noNetFond':'لا يوجد انترنت',
 'confirmPasswordValidateError':'كلمة المرور غير متطابق',
 'canNotStartWithSpace':'لايمكن ان تبدا بمسافة',
 'canNotEndWithSpace':'لايمكن ان تنتهي بمسافة',
 'example':'مثال :',
 'arabic':'العربية',
 'english':'English',
 'camera':'الكيمراء',
 'gallery' : 'الاستوديو',
 'cancel' : 'الغاء',
 'confirmationDelete' : 'تاكيد عملية الحذف',
 'lostInterNet' : 'تم فقداً الاتصال بالانترنت',
 'unKnowError' : 'حصل خطاء ما يرجاء اعادة المحاولة',
 'error' : 'خطاء',
 'required' : 'مطلوب',
 'password' : 'كلمة السر',
 'confirmPassword' : 'تاكيد كلمة السر',
 'phoneNumber' : 'رقم الموبايل',
 'forgetPassword' : 'نسيت كلمة السر !',
 'login' : 'تسجيل الدخول',
 'or' : 'او',
 'image' : 'صورة',
 'createAcount' : 'انشاء حساب',
 'email' : 'البريد الالكتروني',
 'close' : 'اغلاق',
 'save' : 'حفظ',
 'noData' : 'لا يوجد بيانات',
 'processes' : 'العمليات',
 'confirmation' : 'تـأكيد',
 'imageNotSelectImage' : 'لم يتم اختيار اي صورة',
 'canNotAccessTo' : ' لا يمكن الوصول الى ',
 'searchFor' : 'البحث عن',
 'fetchingData' : 'جاري جلب',
 'profile':'حسابي',
 'home':'الرئيسية',
 'actions' : 'الاجراءت',
 'noDataFound' : 'لا يوجد بيانات لعرضها',
 'fullName' : 'الاسم الرباعي',
 'subscriptionNumber':'رقم الاشتراك',
 'exitAccountMsg':'هل تريد حقا تسجيل الخروج من الحساب',
 'account':'الحساب',
 'changePassword' : 'تغيير كلمة المرور',
 'pressHereToChangePassword':'اضغط هنا لتغيير كلمة المرور',
 'notifications':'الاشعارات',
 'pressHereToShowAll':'اضغط هنا لعرض جميع',
 'pressToChangLanguge':'اضفط هنا لتغير لغه التطبيق',
 'changTheme':'تغير الثيم',
 'pressToChangTheme':'اضغط هنا لتغير الثيم',
 'aboutApp':'عن التطبيق',
 'pressToShowAboutApp':'اضغط هنا لعرض جميع مايتعلق التطبيق',
 'exitAccount':'تسجيل الخروج',
 'deleteAccount':'حذف حسابي',
 'pressToDeleteAccount':'اضفط هنا لحذف الحساب',
 'pressToExitAccount':'اضفط هنا لتسجيل الخروج من الحساب',
 'byCratingAccountYouAgreeToOur':'عند انشاءك حساب فانك توافق على ',
 'termsOfService':'شروط الخدمة ',
 'privacyPolicy':'سياسة الخصوصية',
 'and':' و ',
 'title3':'شرح مختصر',
 'title2':'شرح مختصر',
 'title1':'شرح مختصر',
 'reports' : 'التقارير',
 'support' : 'الدعم',
 'managementAndController':'الادارة والتحكم',
 'welcome' : ' مرحبا بكم',
 'notCompleted' : ' لم يكتمل ',
 'notAcceptTextValue' : 'لا يقبل قيمة نصية او فراغ',
 'pleaseEnterTheConfirmationCodeThatWasSentYou':'يرجى ادخال رمز التاكيد الذي تم ارساله اليك',
};