Map<String, String> en = {
 'appName':'     Feasibility Study',
 'language':'language',
 'noNetFond':'No Net Fond',
 'confirmPasswordValidateError':'Password does not match',
 'canNotStartWithSpace':'Can Not Start With Space',
 'canNotEndWithSpace':'Can Not End With Space',
 'photo':'photo',
 'home':'Home',
 'pressToExitAccount':'Press To Exit Account',
 'pressHereToChangePassword':'Press Here To Change Password',
 'pleaseEnterTheConfirmationCodeThatWasSentYou':'Please Enter The Confirmation Code That Was Sent You',
 'example':'example :',
 'arabic':'arabic',
 'english':'English',
 'camera':'Camera',
 'gallery' : 'Gallery',
 'cancel' : 'Cancel',
 'notCompleted' : 'Not Completed',
 'notAcceptTextValue' : 'Not Accept Text Value',
 'confirmationDelete' : 'Confirm The Deletion',
 'lostInterNet' : 'Internet connection has been lost',
 'unKnowError' : 'An error occurred, please try again',
 'error' : 'error',
 'required' : 'required',
 'password' : 'Password',
 'confirmPassword' : 'Confirm Password',
 'phoneNumber' : 'phone Number',
 'forgetPassword' : 'Forget Password !',
 'login' : 'Login',
 'or' : 'Or',
 'image' : 'Image',
 'createAcount' : 'Create Account',
 'email' : 'email',
 'close' : 'close',
 'save' : 'save',
 'noData' : 'No Data',
 'processes' : 'Processes',
 'confirmation' : 'Confirmation',
 'imageNotSelectImage' : 'No photo was selected',
 'canNotAccessTo' : 'Can Not Access To',
 'searchFor' : 'Search For',
 'fetchingData' : 'Data is being fetched',
 'noDataFound' : 'No Data Found',
 'noNetFound' : 'No Internet Connection',
 'reports' : 'Reports',
 'support' : 'Support',
 'profile' : 'Profile',
 'actions' : 'Actions',
 'fullName' : 'Full Name',
 'subscriptionNumber':'Subscription Number',
 'exitAccountMsg':'exit Account Msg',
 'account':'Account',
 'changePassword' : 'Change Password',
 'notifications':'Notifications',
 'pressHereToShowAll':'Press Here To Show All',
 'pressToChangLanguge':'Press To Chang Languge',
 'changTheme':'Chang Theme',
 'pressToChangTheme':'Press To Chang Theme ',
 'aboutApp':'About App',
 'pressToShowAboutApp':'Press To Show About App',
 'exitAccount':'Exit Account',
 'deleteAccount':'Delete Account',
 'byCratingAccountYouAgreeToOur':'By Crating Account You Agree To Our ',
 'termsOfService':'Terms Of Service ',
 'and':'And',
 'privacyPolicy':'Privacy Policy ',
 'title3':'Print daily, weekly and monthly reports and draw charts',
 'title2':'Manage tables, products, branches, tax and control customers and users',
 'title1':'Supports electronic scales, barcodes and all types of printers',
 'managementAndController':'Management And Controller',
 'welcome' : 'Welcome',
};